/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as unguardedUnguarded_layoutRouteImport } from './routes/(unguarded)/_unguarded_layout'
import { Route as authAuth_layoutRouteImport } from './routes/(auth)/_auth_layout'
import { Route as unguardedUnguarded_layoutLoginIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/login/index'
import { Route as authAuth_layoutAppIndexRouteImport } from './routes/(auth)/_auth_layout/app/index'
import { Route as authAuth_layoutAppWebhooksIndexRouteImport } from './routes/(auth)/_auth_layout/app/webhooks/index'
import { Route as authAuth_layoutAppVerificationSettingsIndexRouteImport } from './routes/(auth)/_auth_layout/app/verification-settings/index'
import { Route as authAuth_layoutAppUsersIndexRouteImport } from './routes/(auth)/_auth_layout/app/users/index'
import { Route as authAuth_layoutAppTopUpsIndexRouteImport } from './routes/(auth)/_auth_layout/app/top-ups/index'
import { Route as authAuth_layoutAppTenantsIndexRouteImport } from './routes/(auth)/_auth_layout/app/tenants/index'
import { Route as authAuth_layoutAppMixedVerificationsIndexRouteImport } from './routes/(auth)/_auth_layout/app/mixed-verifications/index'
import { Route as authAuth_layoutAppInvoicesIndexRouteImport } from './routes/(auth)/_auth_layout/app/invoices/index'
import { Route as authAuth_layoutAppActivityLogsIndexRouteImport } from './routes/(auth)/_auth_layout/app/activity-logs/index'
import { Route as authAuth_layoutAppTenantsTenantIdIndexRouteImport } from './routes/(auth)/_auth_layout/app/tenants/$tenantId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const unguardedUnguarded_layoutRoute =
  unguardedUnguarded_layoutRouteImport.update({
    id: '/(unguarded)/_unguarded_layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuth_layoutRoute = authAuth_layoutRouteImport.update({
  id: '/(auth)/_auth_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const unguardedUnguarded_layoutLoginIndexRoute =
  unguardedUnguarded_layoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const authAuth_layoutAppIndexRoute = authAuth_layoutAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => authAuth_layoutRoute,
} as any)
const authAuth_layoutAppWebhooksIndexRoute =
  authAuth_layoutAppWebhooksIndexRouteImport.update({
    id: '/app/webhooks/',
    path: '/app/webhooks/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppVerificationSettingsIndexRoute =
  authAuth_layoutAppVerificationSettingsIndexRouteImport.update({
    id: '/app/verification-settings/',
    path: '/app/verification-settings/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppUsersIndexRoute =
  authAuth_layoutAppUsersIndexRouteImport.update({
    id: '/app/users/',
    path: '/app/users/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppTopUpsIndexRoute =
  authAuth_layoutAppTopUpsIndexRouteImport.update({
    id: '/app/top-ups/',
    path: '/app/top-ups/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppTenantsIndexRoute =
  authAuth_layoutAppTenantsIndexRouteImport.update({
    id: '/app/tenants/',
    path: '/app/tenants/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppMixedVerificationsIndexRoute =
  authAuth_layoutAppMixedVerificationsIndexRouteImport.update({
    id: '/app/mixed-verifications/',
    path: '/app/mixed-verifications/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppInvoicesIndexRoute =
  authAuth_layoutAppInvoicesIndexRouteImport.update({
    id: '/app/invoices/',
    path: '/app/invoices/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppActivityLogsIndexRoute =
  authAuth_layoutAppActivityLogsIndexRouteImport.update({
    id: '/app/activity-logs/',
    path: '/app/activity-logs/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppTenantsTenantIdIndexRoute =
  authAuth_layoutAppTenantsTenantIdIndexRouteImport.update({
    id: '/app/tenants/$tenantId/',
    path: '/app/tenants/$tenantId/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/': typeof authAuth_layoutAppIndexRoute
  '/login/': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/app/activity-logs/': typeof authAuth_layoutAppActivityLogsIndexRoute
  '/app/invoices/': typeof authAuth_layoutAppInvoicesIndexRoute
  '/app/mixed-verifications/': typeof authAuth_layoutAppMixedVerificationsIndexRoute
  '/app/tenants/': typeof authAuth_layoutAppTenantsIndexRoute
  '/app/top-ups/': typeof authAuth_layoutAppTopUpsIndexRoute
  '/app/users/': typeof authAuth_layoutAppUsersIndexRoute
  '/app/verification-settings/': typeof authAuth_layoutAppVerificationSettingsIndexRoute
  '/app/webhooks/': typeof authAuth_layoutAppWebhooksIndexRoute
  '/app/tenants/$tenantId/': typeof authAuth_layoutAppTenantsTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof authAuth_layoutAppIndexRoute
  '/login': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/app/activity-logs': typeof authAuth_layoutAppActivityLogsIndexRoute
  '/app/invoices': typeof authAuth_layoutAppInvoicesIndexRoute
  '/app/mixed-verifications': typeof authAuth_layoutAppMixedVerificationsIndexRoute
  '/app/tenants': typeof authAuth_layoutAppTenantsIndexRoute
  '/app/top-ups': typeof authAuth_layoutAppTopUpsIndexRoute
  '/app/users': typeof authAuth_layoutAppUsersIndexRoute
  '/app/verification-settings': typeof authAuth_layoutAppVerificationSettingsIndexRoute
  '/app/webhooks': typeof authAuth_layoutAppWebhooksIndexRoute
  '/app/tenants/$tenantId': typeof authAuth_layoutAppTenantsTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth_layout': typeof authAuth_layoutRouteWithChildren
  '/(unguarded)/_unguarded_layout': typeof unguardedUnguarded_layoutRouteWithChildren
  '/(auth)/_auth_layout/app/': typeof authAuth_layoutAppIndexRoute
  '/(unguarded)/_unguarded_layout/login/': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/(auth)/_auth_layout/app/activity-logs/': typeof authAuth_layoutAppActivityLogsIndexRoute
  '/(auth)/_auth_layout/app/invoices/': typeof authAuth_layoutAppInvoicesIndexRoute
  '/(auth)/_auth_layout/app/mixed-verifications/': typeof authAuth_layoutAppMixedVerificationsIndexRoute
  '/(auth)/_auth_layout/app/tenants/': typeof authAuth_layoutAppTenantsIndexRoute
  '/(auth)/_auth_layout/app/top-ups/': typeof authAuth_layoutAppTopUpsIndexRoute
  '/(auth)/_auth_layout/app/users/': typeof authAuth_layoutAppUsersIndexRoute
  '/(auth)/_auth_layout/app/verification-settings/': typeof authAuth_layoutAppVerificationSettingsIndexRoute
  '/(auth)/_auth_layout/app/webhooks/': typeof authAuth_layoutAppWebhooksIndexRoute
  '/(auth)/_auth_layout/app/tenants/$tenantId/': typeof authAuth_layoutAppTenantsTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/'
    | '/login/'
    | '/app/activity-logs/'
    | '/app/invoices/'
    | '/app/mixed-verifications/'
    | '/app/tenants/'
    | '/app/top-ups/'
    | '/app/users/'
    | '/app/verification-settings/'
    | '/app/webhooks/'
    | '/app/tenants/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/activity-logs'
    | '/app/invoices'
    | '/app/mixed-verifications'
    | '/app/tenants'
    | '/app/top-ups'
    | '/app/users'
    | '/app/verification-settings'
    | '/app/webhooks'
    | '/app/tenants/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth_layout'
    | '/(unguarded)/_unguarded_layout'
    | '/(auth)/_auth_layout/app/'
    | '/(unguarded)/_unguarded_layout/login/'
    | '/(auth)/_auth_layout/app/activity-logs/'
    | '/(auth)/_auth_layout/app/invoices/'
    | '/(auth)/_auth_layout/app/mixed-verifications/'
    | '/(auth)/_auth_layout/app/tenants/'
    | '/(auth)/_auth_layout/app/top-ups/'
    | '/(auth)/_auth_layout/app/users/'
    | '/(auth)/_auth_layout/app/verification-settings/'
    | '/(auth)/_auth_layout/app/webhooks/'
    | '/(auth)/_auth_layout/app/tenants/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuth_layoutRoute: typeof authAuth_layoutRouteWithChildren
  unguardedUnguarded_layoutRoute: typeof unguardedUnguarded_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unguarded)/_unguarded_layout': {
      id: '/(unguarded)/_unguarded_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unguardedUnguarded_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth_layout': {
      id: '/(auth)/_auth_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unguarded)/_unguarded_layout/login/': {
      id: '/(unguarded)/_unguarded_layout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof unguardedUnguarded_layoutLoginIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(auth)/_auth_layout/app/': {
      id: '/(auth)/_auth_layout/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof authAuth_layoutAppIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/webhooks/': {
      id: '/(auth)/_auth_layout/app/webhooks/'
      path: '/app/webhooks'
      fullPath: '/app/webhooks/'
      preLoaderRoute: typeof authAuth_layoutAppWebhooksIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/verification-settings/': {
      id: '/(auth)/_auth_layout/app/verification-settings/'
      path: '/app/verification-settings'
      fullPath: '/app/verification-settings/'
      preLoaderRoute: typeof authAuth_layoutAppVerificationSettingsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/users/': {
      id: '/(auth)/_auth_layout/app/users/'
      path: '/app/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof authAuth_layoutAppUsersIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/top-ups/': {
      id: '/(auth)/_auth_layout/app/top-ups/'
      path: '/app/top-ups'
      fullPath: '/app/top-ups/'
      preLoaderRoute: typeof authAuth_layoutAppTopUpsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/tenants/': {
      id: '/(auth)/_auth_layout/app/tenants/'
      path: '/app/tenants'
      fullPath: '/app/tenants/'
      preLoaderRoute: typeof authAuth_layoutAppTenantsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/mixed-verifications/': {
      id: '/(auth)/_auth_layout/app/mixed-verifications/'
      path: '/app/mixed-verifications'
      fullPath: '/app/mixed-verifications/'
      preLoaderRoute: typeof authAuth_layoutAppMixedVerificationsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/invoices/': {
      id: '/(auth)/_auth_layout/app/invoices/'
      path: '/app/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof authAuth_layoutAppInvoicesIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/activity-logs/': {
      id: '/(auth)/_auth_layout/app/activity-logs/'
      path: '/app/activity-logs'
      fullPath: '/app/activity-logs/'
      preLoaderRoute: typeof authAuth_layoutAppActivityLogsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/tenants/$tenantId/': {
      id: '/(auth)/_auth_layout/app/tenants/$tenantId/'
      path: '/app/tenants/$tenantId'
      fullPath: '/app/tenants/$tenantId/'
      preLoaderRoute: typeof authAuth_layoutAppTenantsTenantIdIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
  }
}

interface authAuth_layoutRouteChildren {
  authAuth_layoutAppIndexRoute: typeof authAuth_layoutAppIndexRoute
  authAuth_layoutAppActivityLogsIndexRoute: typeof authAuth_layoutAppActivityLogsIndexRoute
  authAuth_layoutAppInvoicesIndexRoute: typeof authAuth_layoutAppInvoicesIndexRoute
  authAuth_layoutAppMixedVerificationsIndexRoute: typeof authAuth_layoutAppMixedVerificationsIndexRoute
  authAuth_layoutAppTenantsIndexRoute: typeof authAuth_layoutAppTenantsIndexRoute
  authAuth_layoutAppTopUpsIndexRoute: typeof authAuth_layoutAppTopUpsIndexRoute
  authAuth_layoutAppUsersIndexRoute: typeof authAuth_layoutAppUsersIndexRoute
  authAuth_layoutAppVerificationSettingsIndexRoute: typeof authAuth_layoutAppVerificationSettingsIndexRoute
  authAuth_layoutAppWebhooksIndexRoute: typeof authAuth_layoutAppWebhooksIndexRoute
  authAuth_layoutAppTenantsTenantIdIndexRoute: typeof authAuth_layoutAppTenantsTenantIdIndexRoute
}

const authAuth_layoutRouteChildren: authAuth_layoutRouteChildren = {
  authAuth_layoutAppIndexRoute: authAuth_layoutAppIndexRoute,
  authAuth_layoutAppActivityLogsIndexRoute:
    authAuth_layoutAppActivityLogsIndexRoute,
  authAuth_layoutAppInvoicesIndexRoute: authAuth_layoutAppInvoicesIndexRoute,
  authAuth_layoutAppMixedVerificationsIndexRoute:
    authAuth_layoutAppMixedVerificationsIndexRoute,
  authAuth_layoutAppTenantsIndexRoute: authAuth_layoutAppTenantsIndexRoute,
  authAuth_layoutAppTopUpsIndexRoute: authAuth_layoutAppTopUpsIndexRoute,
  authAuth_layoutAppUsersIndexRoute: authAuth_layoutAppUsersIndexRoute,
  authAuth_layoutAppVerificationSettingsIndexRoute:
    authAuth_layoutAppVerificationSettingsIndexRoute,
  authAuth_layoutAppWebhooksIndexRoute: authAuth_layoutAppWebhooksIndexRoute,
  authAuth_layoutAppTenantsTenantIdIndexRoute:
    authAuth_layoutAppTenantsTenantIdIndexRoute,
}

const authAuth_layoutRouteWithChildren = authAuth_layoutRoute._addFileChildren(
  authAuth_layoutRouteChildren,
)

interface unguardedUnguarded_layoutRouteChildren {
  unguardedUnguarded_layoutLoginIndexRoute: typeof unguardedUnguarded_layoutLoginIndexRoute
}

const unguardedUnguarded_layoutRouteChildren: unguardedUnguarded_layoutRouteChildren =
  {
    unguardedUnguarded_layoutLoginIndexRoute:
      unguardedUnguarded_layoutLoginIndexRoute,
  }

const unguardedUnguarded_layoutRouteWithChildren =
  unguardedUnguarded_layoutRoute._addFileChildren(
    unguardedUnguarded_layoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuth_layoutRoute: authAuth_layoutRouteWithChildren,
  unguardedUnguarded_layoutRoute: unguardedUnguarded_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
