/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as unguardedUnguarded_layoutRouteImport } from './routes/(unguarded)/_unguarded_layout'
import { Route as authAuth_layoutRouteImport } from './routes/(auth)/_auth_layout'
import { Route as unguardedUnguarded_layoutResetPasswordIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/reset-password/index'
import { Route as unguardedUnguarded_layoutRegisterIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/register/index'
import { Route as unguardedUnguarded_layoutLoginIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/login/index'
import { Route as unguardedUnguarded_layoutInviteIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/invite/index'
import { Route as unguardedUnguarded_layoutForgotPasswordIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/forgot-password/index'
import { Route as unguardedUnguarded_layoutActivateAccountIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/activate-account/index'
import { Route as authAuth_layoutDashboardIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/index'
import { Route as unguardedUnguarded_layoutVerifyResultRouteImport } from './routes/(unguarded)/_unguarded_layout/verify/result'
import { Route as unguardedUnguarded_layoutVerifyLinkIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/verify/$link/index'
import { Route as authAuth_layoutDashboardWebhooksIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/webhooks/index'
import { Route as authAuth_layoutDashboardVerificationSettingsIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/verification-settings/index'
import { Route as authAuth_layoutDashboardUsersIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/users/index'
import { Route as authAuth_layoutDashboardTopUpsIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/top-ups/index'
import { Route as authAuth_layoutDashboardTenantsIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/tenants/index'
import { Route as authAuth_layoutDashboardMixedVerificationsIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/mixed-verifications/index'
import { Route as authAuth_layoutDashboardInvoicesIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/invoices/index'
import { Route as authAuth_layoutDashboardActivityLogsIndexRouteImport } from './routes/(auth)/_auth_layout/dashboard/activity-logs/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const unguardedUnguarded_layoutRoute =
  unguardedUnguarded_layoutRouteImport.update({
    id: '/(unguarded)/_unguarded_layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuth_layoutRoute = authAuth_layoutRouteImport.update({
  id: '/(auth)/_auth_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const unguardedUnguarded_layoutResetPasswordIndexRoute =
  unguardedUnguarded_layoutResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutRegisterIndexRoute =
  unguardedUnguarded_layoutRegisterIndexRouteImport.update({
    id: '/register/',
    path: '/register/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutLoginIndexRoute =
  unguardedUnguarded_layoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutInviteIndexRoute =
  unguardedUnguarded_layoutInviteIndexRouteImport.update({
    id: '/invite/',
    path: '/invite/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutForgotPasswordIndexRoute =
  unguardedUnguarded_layoutForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutActivateAccountIndexRoute =
  unguardedUnguarded_layoutActivateAccountIndexRouteImport.update({
    id: '/activate-account/',
    path: '/activate-account/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const authAuth_layoutDashboardIndexRoute =
  authAuth_layoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerifyResultRoute =
  unguardedUnguarded_layoutVerifyResultRouteImport.update({
    id: '/verify/result',
    path: '/verify/result',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerifyLinkIndexRoute =
  unguardedUnguarded_layoutVerifyLinkIndexRouteImport.update({
    id: '/verify/$link/',
    path: '/verify/$link/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const authAuth_layoutDashboardWebhooksIndexRoute =
  authAuth_layoutDashboardWebhooksIndexRouteImport.update({
    id: '/dashboard/webhooks/',
    path: '/dashboard/webhooks/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutDashboardVerificationSettingsIndexRoute =
  authAuth_layoutDashboardVerificationSettingsIndexRouteImport.update({
    id: '/dashboard/verification-settings/',
    path: '/dashboard/verification-settings/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutDashboardUsersIndexRoute =
  authAuth_layoutDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutDashboardTopUpsIndexRoute =
  authAuth_layoutDashboardTopUpsIndexRouteImport.update({
    id: '/dashboard/top-ups/',
    path: '/dashboard/top-ups/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutDashboardTenantsIndexRoute =
  authAuth_layoutDashboardTenantsIndexRouteImport.update({
    id: '/dashboard/tenants/',
    path: '/dashboard/tenants/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutDashboardMixedVerificationsIndexRoute =
  authAuth_layoutDashboardMixedVerificationsIndexRouteImport.update({
    id: '/dashboard/mixed-verifications/',
    path: '/dashboard/mixed-verifications/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutDashboardInvoicesIndexRoute =
  authAuth_layoutDashboardInvoicesIndexRouteImport.update({
    id: '/dashboard/invoices/',
    path: '/dashboard/invoices/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutDashboardActivityLogsIndexRoute =
  authAuth_layoutDashboardActivityLogsIndexRouteImport.update({
    id: '/dashboard/activity-logs/',
    path: '/dashboard/activity-logs/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/dashboard/': typeof authAuth_layoutDashboardIndexRoute
  '/activate-account/': typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  '/forgot-password/': typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  '/invite/': typeof unguardedUnguarded_layoutInviteIndexRoute
  '/login/': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/register/': typeof unguardedUnguarded_layoutRegisterIndexRoute
  '/reset-password/': typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  '/dashboard/activity-logs/': typeof authAuth_layoutDashboardActivityLogsIndexRoute
  '/dashboard/invoices/': typeof authAuth_layoutDashboardInvoicesIndexRoute
  '/dashboard/mixed-verifications/': typeof authAuth_layoutDashboardMixedVerificationsIndexRoute
  '/dashboard/tenants/': typeof authAuth_layoutDashboardTenantsIndexRoute
  '/dashboard/top-ups/': typeof authAuth_layoutDashboardTopUpsIndexRoute
  '/dashboard/users/': typeof authAuth_layoutDashboardUsersIndexRoute
  '/dashboard/verification-settings/': typeof authAuth_layoutDashboardVerificationSettingsIndexRoute
  '/dashboard/webhooks/': typeof authAuth_layoutDashboardWebhooksIndexRoute
  '/verify/$link/': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/dashboard': typeof authAuth_layoutDashboardIndexRoute
  '/activate-account': typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  '/forgot-password': typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  '/invite': typeof unguardedUnguarded_layoutInviteIndexRoute
  '/login': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/register': typeof unguardedUnguarded_layoutRegisterIndexRoute
  '/reset-password': typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  '/dashboard/activity-logs': typeof authAuth_layoutDashboardActivityLogsIndexRoute
  '/dashboard/invoices': typeof authAuth_layoutDashboardInvoicesIndexRoute
  '/dashboard/mixed-verifications': typeof authAuth_layoutDashboardMixedVerificationsIndexRoute
  '/dashboard/tenants': typeof authAuth_layoutDashboardTenantsIndexRoute
  '/dashboard/top-ups': typeof authAuth_layoutDashboardTopUpsIndexRoute
  '/dashboard/users': typeof authAuth_layoutDashboardUsersIndexRoute
  '/dashboard/verification-settings': typeof authAuth_layoutDashboardVerificationSettingsIndexRoute
  '/dashboard/webhooks': typeof authAuth_layoutDashboardWebhooksIndexRoute
  '/verify/$link': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth_layout': typeof authAuth_layoutRouteWithChildren
  '/(unguarded)/_unguarded_layout': typeof unguardedUnguarded_layoutRouteWithChildren
  '/(unguarded)/_unguarded_layout/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/(auth)/_auth_layout/dashboard/': typeof authAuth_layoutDashboardIndexRoute
  '/(unguarded)/_unguarded_layout/activate-account/': typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  '/(unguarded)/_unguarded_layout/forgot-password/': typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  '/(unguarded)/_unguarded_layout/invite/': typeof unguardedUnguarded_layoutInviteIndexRoute
  '/(unguarded)/_unguarded_layout/login/': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/(unguarded)/_unguarded_layout/register/': typeof unguardedUnguarded_layoutRegisterIndexRoute
  '/(unguarded)/_unguarded_layout/reset-password/': typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  '/(auth)/_auth_layout/dashboard/activity-logs/': typeof authAuth_layoutDashboardActivityLogsIndexRoute
  '/(auth)/_auth_layout/dashboard/invoices/': typeof authAuth_layoutDashboardInvoicesIndexRoute
  '/(auth)/_auth_layout/dashboard/mixed-verifications/': typeof authAuth_layoutDashboardMixedVerificationsIndexRoute
  '/(auth)/_auth_layout/dashboard/tenants/': typeof authAuth_layoutDashboardTenantsIndexRoute
  '/(auth)/_auth_layout/dashboard/top-ups/': typeof authAuth_layoutDashboardTopUpsIndexRoute
  '/(auth)/_auth_layout/dashboard/users/': typeof authAuth_layoutDashboardUsersIndexRoute
  '/(auth)/_auth_layout/dashboard/verification-settings/': typeof authAuth_layoutDashboardVerificationSettingsIndexRoute
  '/(auth)/_auth_layout/dashboard/webhooks/': typeof authAuth_layoutDashboardWebhooksIndexRoute
  '/(unguarded)/_unguarded_layout/verify/$link/': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify/result'
    | '/dashboard/'
    | '/activate-account/'
    | '/forgot-password/'
    | '/invite/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/dashboard/activity-logs/'
    | '/dashboard/invoices/'
    | '/dashboard/mixed-verifications/'
    | '/dashboard/tenants/'
    | '/dashboard/top-ups/'
    | '/dashboard/users/'
    | '/dashboard/verification-settings/'
    | '/dashboard/webhooks/'
    | '/verify/$link/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify/result'
    | '/dashboard'
    | '/activate-account'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/activity-logs'
    | '/dashboard/invoices'
    | '/dashboard/mixed-verifications'
    | '/dashboard/tenants'
    | '/dashboard/top-ups'
    | '/dashboard/users'
    | '/dashboard/verification-settings'
    | '/dashboard/webhooks'
    | '/verify/$link'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth_layout'
    | '/(unguarded)/_unguarded_layout'
    | '/(unguarded)/_unguarded_layout/verify/result'
    | '/(auth)/_auth_layout/dashboard/'
    | '/(unguarded)/_unguarded_layout/activate-account/'
    | '/(unguarded)/_unguarded_layout/forgot-password/'
    | '/(unguarded)/_unguarded_layout/invite/'
    | '/(unguarded)/_unguarded_layout/login/'
    | '/(unguarded)/_unguarded_layout/register/'
    | '/(unguarded)/_unguarded_layout/reset-password/'
    | '/(auth)/_auth_layout/dashboard/activity-logs/'
    | '/(auth)/_auth_layout/dashboard/invoices/'
    | '/(auth)/_auth_layout/dashboard/mixed-verifications/'
    | '/(auth)/_auth_layout/dashboard/tenants/'
    | '/(auth)/_auth_layout/dashboard/top-ups/'
    | '/(auth)/_auth_layout/dashboard/users/'
    | '/(auth)/_auth_layout/dashboard/verification-settings/'
    | '/(auth)/_auth_layout/dashboard/webhooks/'
    | '/(unguarded)/_unguarded_layout/verify/$link/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuth_layoutRoute: typeof authAuth_layoutRouteWithChildren
  unguardedUnguarded_layoutRoute: typeof unguardedUnguarded_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unguarded)/_unguarded_layout': {
      id: '/(unguarded)/_unguarded_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unguardedUnguarded_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth_layout': {
      id: '/(auth)/_auth_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unguarded)/_unguarded_layout/reset-password/': {
      id: '/(unguarded)/_unguarded_layout/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof unguardedUnguarded_layoutResetPasswordIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/register/': {
      id: '/(unguarded)/_unguarded_layout/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof unguardedUnguarded_layoutRegisterIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/login/': {
      id: '/(unguarded)/_unguarded_layout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof unguardedUnguarded_layoutLoginIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/invite/': {
      id: '/(unguarded)/_unguarded_layout/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof unguardedUnguarded_layoutInviteIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/forgot-password/': {
      id: '/(unguarded)/_unguarded_layout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof unguardedUnguarded_layoutForgotPasswordIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/activate-account/': {
      id: '/(unguarded)/_unguarded_layout/activate-account/'
      path: '/activate-account'
      fullPath: '/activate-account/'
      preLoaderRoute: typeof unguardedUnguarded_layoutActivateAccountIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/': {
      id: '/(auth)/_auth_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authAuth_layoutDashboardIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verify/result': {
      id: '/(unguarded)/_unguarded_layout/verify/result'
      path: '/verify/result'
      fullPath: '/verify/result'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerifyResultRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verify/$link/': {
      id: '/(unguarded)/_unguarded_layout/verify/$link/'
      path: '/verify/$link'
      fullPath: '/verify/$link/'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerifyLinkIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/webhooks/': {
      id: '/(auth)/_auth_layout/dashboard/webhooks/'
      path: '/dashboard/webhooks'
      fullPath: '/dashboard/webhooks/'
      preLoaderRoute: typeof authAuth_layoutDashboardWebhooksIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/verification-settings/': {
      id: '/(auth)/_auth_layout/dashboard/verification-settings/'
      path: '/dashboard/verification-settings'
      fullPath: '/dashboard/verification-settings/'
      preLoaderRoute: typeof authAuth_layoutDashboardVerificationSettingsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/users/': {
      id: '/(auth)/_auth_layout/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof authAuth_layoutDashboardUsersIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/top-ups/': {
      id: '/(auth)/_auth_layout/dashboard/top-ups/'
      path: '/dashboard/top-ups'
      fullPath: '/dashboard/top-ups/'
      preLoaderRoute: typeof authAuth_layoutDashboardTopUpsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/tenants/': {
      id: '/(auth)/_auth_layout/dashboard/tenants/'
      path: '/dashboard/tenants'
      fullPath: '/dashboard/tenants/'
      preLoaderRoute: typeof authAuth_layoutDashboardTenantsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/mixed-verifications/': {
      id: '/(auth)/_auth_layout/dashboard/mixed-verifications/'
      path: '/dashboard/mixed-verifications'
      fullPath: '/dashboard/mixed-verifications/'
      preLoaderRoute: typeof authAuth_layoutDashboardMixedVerificationsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/invoices/': {
      id: '/(auth)/_auth_layout/dashboard/invoices/'
      path: '/dashboard/invoices'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof authAuth_layoutDashboardInvoicesIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/dashboard/activity-logs/': {
      id: '/(auth)/_auth_layout/dashboard/activity-logs/'
      path: '/dashboard/activity-logs'
      fullPath: '/dashboard/activity-logs/'
      preLoaderRoute: typeof authAuth_layoutDashboardActivityLogsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
  }
}

interface authAuth_layoutRouteChildren {
  authAuth_layoutDashboardIndexRoute: typeof authAuth_layoutDashboardIndexRoute
  authAuth_layoutDashboardActivityLogsIndexRoute: typeof authAuth_layoutDashboardActivityLogsIndexRoute
  authAuth_layoutDashboardInvoicesIndexRoute: typeof authAuth_layoutDashboardInvoicesIndexRoute
  authAuth_layoutDashboardMixedVerificationsIndexRoute: typeof authAuth_layoutDashboardMixedVerificationsIndexRoute
  authAuth_layoutDashboardTenantsIndexRoute: typeof authAuth_layoutDashboardTenantsIndexRoute
  authAuth_layoutDashboardTopUpsIndexRoute: typeof authAuth_layoutDashboardTopUpsIndexRoute
  authAuth_layoutDashboardUsersIndexRoute: typeof authAuth_layoutDashboardUsersIndexRoute
  authAuth_layoutDashboardVerificationSettingsIndexRoute: typeof authAuth_layoutDashboardVerificationSettingsIndexRoute
  authAuth_layoutDashboardWebhooksIndexRoute: typeof authAuth_layoutDashboardWebhooksIndexRoute
}

const authAuth_layoutRouteChildren: authAuth_layoutRouteChildren = {
  authAuth_layoutDashboardIndexRoute: authAuth_layoutDashboardIndexRoute,
  authAuth_layoutDashboardActivityLogsIndexRoute:
    authAuth_layoutDashboardActivityLogsIndexRoute,
  authAuth_layoutDashboardInvoicesIndexRoute:
    authAuth_layoutDashboardInvoicesIndexRoute,
  authAuth_layoutDashboardMixedVerificationsIndexRoute:
    authAuth_layoutDashboardMixedVerificationsIndexRoute,
  authAuth_layoutDashboardTenantsIndexRoute:
    authAuth_layoutDashboardTenantsIndexRoute,
  authAuth_layoutDashboardTopUpsIndexRoute:
    authAuth_layoutDashboardTopUpsIndexRoute,
  authAuth_layoutDashboardUsersIndexRoute:
    authAuth_layoutDashboardUsersIndexRoute,
  authAuth_layoutDashboardVerificationSettingsIndexRoute:
    authAuth_layoutDashboardVerificationSettingsIndexRoute,
  authAuth_layoutDashboardWebhooksIndexRoute:
    authAuth_layoutDashboardWebhooksIndexRoute,
}

const authAuth_layoutRouteWithChildren = authAuth_layoutRoute._addFileChildren(
  authAuth_layoutRouteChildren,
)

interface unguardedUnguarded_layoutRouteChildren {
  unguardedUnguarded_layoutVerifyResultRoute: typeof unguardedUnguarded_layoutVerifyResultRoute
  unguardedUnguarded_layoutActivateAccountIndexRoute: typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  unguardedUnguarded_layoutForgotPasswordIndexRoute: typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  unguardedUnguarded_layoutInviteIndexRoute: typeof unguardedUnguarded_layoutInviteIndexRoute
  unguardedUnguarded_layoutLoginIndexRoute: typeof unguardedUnguarded_layoutLoginIndexRoute
  unguardedUnguarded_layoutRegisterIndexRoute: typeof unguardedUnguarded_layoutRegisterIndexRoute
  unguardedUnguarded_layoutResetPasswordIndexRoute: typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  unguardedUnguarded_layoutVerifyLinkIndexRoute: typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}

const unguardedUnguarded_layoutRouteChildren: unguardedUnguarded_layoutRouteChildren =
  {
    unguardedUnguarded_layoutVerifyResultRoute:
      unguardedUnguarded_layoutVerifyResultRoute,
    unguardedUnguarded_layoutActivateAccountIndexRoute:
      unguardedUnguarded_layoutActivateAccountIndexRoute,
    unguardedUnguarded_layoutForgotPasswordIndexRoute:
      unguardedUnguarded_layoutForgotPasswordIndexRoute,
    unguardedUnguarded_layoutInviteIndexRoute:
      unguardedUnguarded_layoutInviteIndexRoute,
    unguardedUnguarded_layoutLoginIndexRoute:
      unguardedUnguarded_layoutLoginIndexRoute,
    unguardedUnguarded_layoutRegisterIndexRoute:
      unguardedUnguarded_layoutRegisterIndexRoute,
    unguardedUnguarded_layoutResetPasswordIndexRoute:
      unguardedUnguarded_layoutResetPasswordIndexRoute,
    unguardedUnguarded_layoutVerifyLinkIndexRoute:
      unguardedUnguarded_layoutVerifyLinkIndexRoute,
  }

const unguardedUnguarded_layoutRouteWithChildren =
  unguardedUnguarded_layoutRoute._addFileChildren(
    unguardedUnguarded_layoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuth_layoutRoute: authAuth_layoutRouteWithChildren,
  unguardedUnguarded_layoutRoute: unguardedUnguarded_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
